server:
  port:8100
spring:
  application:
    name: userProvider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

#mybatis的配置
mybatis:
  type-aliases-package: com.fptrade.provider.fptraderprovideruser.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.fptrade.provider.fptraderprovideruser.dao: debug


