server:
  port: 8103
spring:
  application:
    name: userProvider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bishe
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#mybatis
mybatis:
  type-aliases-package: com.fptrade.provider.fptradeprovidertrade.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.fptrade.provider.fptraderprovideruser.dao: debug
